/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.Statement;
import dataBase.koneksiDatabase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class viewListDataBarang extends javax.swing.JFrame {

    /**
     * Creates new form viewListDataBarang
     */
    //inisialisasi untuk menghubungkan form ini ke form transaksi
    
    private viewTransaksi vT;
    //inisialisasi tabel model
    private DefaultTableModel model;
    //inisialisasi variabel untuk menyimpan query ke database
    private String sql = "";
    
    
    public viewListDataBarang(/*menghubungkan ke form transaksi*/ viewTransaksi vT) {
        initComponents();
        
        this.vT = vT;
        
        //inisialisasi kolom tabel
        model = new DefaultTableModel();
        tabelDataBarang.setModel(model);
        model.addColumn("id barang");
        model.addColumn("nama barang");
        model.addColumn("jenis barang");
        model.addColumn("Satuan barang");
        model.addColumn("ukuran");
        model.addColumn("Stok");
        model.addColumn("harga");
        
        //fungsi untuk menampilkan barangketika pertama kali dibuka
        
        tampilDataBarang("");
    }
    
    //fungsi untuk mengambil data barang dari db
    //satu fungsi akan digunakan untuk dua kondisi
    //yaitu untuk menampilkan seluruh data barang
    //dan menampilkan data barang berdasarkan pencarian
    private void tampilDataBarang(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        //kondisi pengecekan, apakah yang dicarinya 
        //seluruh data barang, atau salah satu saja
        if(data.equals("")){
            sql = "select * from barang";
        } else sql = "select * from barang where namaBarang LIKE '"+data+"%'"; //<<memakai persen
        
        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            //proses pengambilan data hasil query
            while(res.next()){
                Object[] hasil;
                hasil = new Object[7]; //jumlah object sesuaikan
                
                hasil[0] = res.getString("idBarang");
                hasil[1] = res.getString("namaBarang");
                hasil[2] = res.getString("jenisBarang");
                hasil[3] = res.getString("satuan");
                hasil[4] = res.getString("ukuran");
                hasil[5] = res.getString("stok");
                hasil[6] = res.getString("harga");
                
                
                model.addRow(hasil);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewListDataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Daftar Barang");

        jLabel2.setText("Cari Nama Barang");

        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });
        namaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaBarangKeyPressed(evt);
            }
        });

        tabelDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaBarangKeyPressed
        // TODO add your handling code here:
        //fungsi ini akan dieksekusi ketika kita mencari nama barang
        tampilDataBarang(namaBarang.getText());
    }//GEN-LAST:event_namaBarangKeyPressed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangActionPerformed

    private void tabelDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataBarangMouseClicked
        // TODO add your handling code here:
        int ambilRow = tabelDataBarang.getSelectedRow();
        vT.getNamaBarang().setText(tabelDataBarang.getValueAt(ambilRow, 1).toString());
        vT.getHargaBarang().setText(tabelDataBarang.getValueAt(ambilRow, 6).toString());
        
        vT.getHargaBarang().requestFocus();
        this.dispose();
    }//GEN-LAST:event_tabelDataBarangMouseClicked

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTable tabelDataBarang;
    // End of variables declaration//GEN-END:variables
}
