/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.controllerBarang;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import controller.controllerPemasokBarang;
import dataBase.koneksiDatabase;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import controller.controllerBarang;
/**
 *
 * @author Asus
 */
public class viewPemasokBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewPemasokBarang
     */
    private controllerPemasokBarang cPB;
    private DefaultTableModel model;
    private controllerBarang cB;
    private DefaultTableModel modelBarang;
    public viewPemasokBarang() {
        initComponents();
        cPB = new controllerPemasokBarang(this);
        modelBarang = new DefaultTableModel();
        tabelBarang.setModel(modelBarang);
        modelBarang.addColumn("Nama");
        modelBarang.addColumn("Jenis");
        modelBarang.addColumn("Satuan");
        modelBarang.addColumn("Ukuran");
        modelBarang.addColumn("Stok");
        modelBarang.addColumn("harga");       
        tampilDataBarang();
        
        
        model = new DefaultTableModel();
        tabelPemasokBarang.setModel(model);
        model.addColumn("Nomer");
        model.addColumn("Nama Perusahaan");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal");
        model.addColumn("Alamat");
        tampilDataPemasokBarang();
        cPB.kontrolButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        nomorIdentitasView = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namaPerusahaanPemasokBarangView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namaBarangPemasokBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        satuanPemasokBarangView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPerusahaanView = new javax.swing.JTextArea();
        tombolTambah = new javax.swing.JButton();
        tombolHapusView = new javax.swing.JButton();
        tombolBatalView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPemasokBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ukuranPemasokBarangView = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jumlahPemasokBarangVieww = new javax.swing.JTextField();
        hargaPersatuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JenisBarangPemasokBarang1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pemasok Barang");

        jLabel6.setText("Nomor");

        nomorIdentitasView.setEnabled(false);
        nomorIdentitasView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorIdentitasViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Perusahaan");

        namaPerusahaanPemasokBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPerusahaanPemasokBarangViewActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Barang");

        namaBarangPemasokBarang.setEnabled(false);
        namaBarangPemasokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangPemasokBarangActionPerformed(evt);
            }
        });

        jLabel3.setText("Satuan");

        satuanPemasokBarangView.setEnabled(false);
        satuanPemasokBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanPemasokBarangViewActionPerformed(evt);
            }
        });

        jLabel5.setText("Alamat Perusahaan");

        alamatPerusahaanView.setColumns(20);
        alamatPerusahaanView.setRows(5);
        jScrollPane1.setViewportView(alamatPerusahaanView);

        tombolTambah.setText("Tambah");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolHapusView.setText("Hapus");
        tombolHapusView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusViewActionPerformed(evt);
            }
        });

        tombolBatalView.setText("Batal");
        tombolBatalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalViewActionPerformed(evt);
            }
        });

        tabelPemasokBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemasokBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemasokBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPemasokBarang);

        jLabel7.setText("Ukuran");

        ukuranPemasokBarangView.setEnabled(false);
        ukuranPemasokBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukuranPemasokBarangViewActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah");

        jumlahPemasokBarangVieww.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPemasokBarangViewwActionPerformed(evt);
            }
        });

        hargaPersatuan.setEnabled(false);
        hargaPersatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaPersatuanActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga");

        jLabel10.setText("Jenis");

        JenisBarangPemasokBarang1.setEnabled(false);
        JenisBarangPemasokBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisBarangPemasokBarang1ActionPerformed(evt);
            }
        });

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaBarangPemasokBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(namaPerusahaanPemasokBarangView, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(nomorIdentitasView, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(JenisBarangPemasokBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(satuanPemasokBarangView, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(ukuranPemasokBarangView)
                            .addComponent(jumlahPemasokBarangVieww)
                            .addComponent(hargaPersatuan)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(tombolBatalView)
                        .addGap(35, 35, 35)
                        .addComponent(tombolHapusView)
                        .addGap(18, 18, 18)
                        .addComponent(tombolTambah)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nomorIdentitasView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(namaPerusahaanPemasokBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(namaBarangPemasokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(JenisBarangPemasokBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(satuanPemasokBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(ukuranPemasokBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jumlahPemasokBarangVieww, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(hargaPersatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tombolTambah)
                                .addComponent(tombolHapusView)
                                .addComponent(tombolBatalView))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomorIdentitasViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorIdentitasViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorIdentitasViewActionPerformed

    private void namaPerusahaanPemasokBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPerusahaanPemasokBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPerusahaanPemasokBarangViewActionPerformed

    private void namaBarangPemasokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangPemasokBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangPemasokBarangActionPerformed

    private void satuanPemasokBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanPemasokBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanPemasokBarangViewActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
        cPB.simpan();
        tampilDataPemasokBarang();
        tampilDataBarang();
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombolHapusViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusViewActionPerformed
        // TODO add your handling code here:
        cPB.hapus();
        tampilDataPemasokBarang();
        tampilDataBarang();
    }//GEN-LAST:event_tombolHapusViewActionPerformed

    private void tombolBatalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalViewActionPerformed
        // TODO add your handling code here:
        cPB.kontrolButton();
        cPB.bersihkan();
        tampilDataPemasokBarang();
        tampilDataBarang();
    }//GEN-LAST:event_tombolBatalViewActionPerformed

    private void tabelPemasokBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemasokBarangMouseClicked
        // TODO add your handling code here:
        ambilDataTabel();
    }//GEN-LAST:event_tabelPemasokBarangMouseClicked

    private void ukuranPemasokBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukuranPemasokBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukuranPemasokBarangViewActionPerformed

    private void jumlahPemasokBarangViewwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPemasokBarangViewwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPemasokBarangViewwActionPerformed

    private void hargaPersatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaPersatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaPersatuanActionPerformed

    private void JenisBarangPemasokBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisBarangPemasokBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisBarangPemasokBarang1ActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        ambilDataTabelBarang();
    }//GEN-LAST:event_tabelBarangMouseClicked

    public DefaultTableModel getModel() {
        return model;
    }

    public JTextField getJenisBarangPemasokBarang1() {
        return JenisBarangPemasokBarang1;
    }
    
    

    public JTextArea getAlamatPerusahaanView() {
        return alamatPerusahaanView;
    }

    public JTextField getHargaPersatuan() {
        return hargaPersatuan;
    }

    public JTextField getIdPemasokBarangView() {
        return nomorIdentitasView;
    }

    public JTextField getJumlahPemasokBarangVieww() {
        return jumlahPemasokBarangVieww;
    }

    public JTextField getNamaBarangPemasokBarang() {
        return namaBarangPemasokBarang;
    }

    public JTextField getNamaPerusahaanPemasokBarangView() {
        return namaPerusahaanPemasokBarangView;
    }

    public JTextField getSatuanPemasokBarangView() {
        return satuanPemasokBarangView;
    }

    public JButton getTombolBatalView() {
        return tombolBatalView;
    }

    public JButton getTombolHapusView() {
        return tombolHapusView;
    }

    public JButton getTombolSimpanView() {
        return tombolTambah;
    }


    public JTextField getUkuranPemasokBarangView() {
        return ukuranPemasokBarangView;
    }
    
    
    
        private void tampilDataPemasokBarang(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = ("SELECT * FROM pemasokbarang");
        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] hasil;
                hasil = new Object[5];
                hasil[0] = res.getString("nomor");
                hasil[1] = res.getString("namaPerusahaan");
                hasil[2] = res.getString("jumlah");
                hasil[3] = res.getString("tanggal");
                hasil[4] = res.getString("alamatPerusahaan");
                model.addRow(hasil);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    private void ambilDataTabel(){
        int index = tabelPemasokBarang.getSelectedRow();
        String nomorIdentitas = String.valueOf(tabelPemasokBarang.getValueAt(index, 0));
        String namaPerusahaan = String.valueOf(tabelPemasokBarang.getValueAt(index, 1));
        String jumlah = String.valueOf(tabelPemasokBarang.getValueAt(index, 2));
        String tanggal = String.valueOf(tabelPemasokBarang.getValueAt(index, 3));
        String alamatPrusahaan = String.valueOf(tabelPemasokBarang.getValueAt(index, 4));
        
        nomorIdentitasView.setText(nomorIdentitas);
        namaPerusahaanPemasokBarangView.setText(namaPerusahaan);
        //jumlahPemasokBarangVieww.setText(jumlah);        
        alamatPerusahaanView.setText(alamatPrusahaan);
        cPB.kontrolButtonDua();
    }
    private void tampilDataBarang(){
        modelBarang.getDataVector().removeAllElements();
        modelBarang.fireTableDataChanged();
        String sql = ("SELECT namaBarang, jenisBarang, satuan, ukuran, stok, harga FROM barang");
        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] hasil;
                hasil = new Object[6];
                hasil[0] = res.getString("namaBarang");
                hasil[1] = res.getString("jenisBarang");
                hasil[2] = res.getString("satuan");
                hasil[3] = res.getString("ukuran");
                hasil[4] = res.getString("stok");
                hasil[5] = res.getString("harga");
                modelBarang.addRow(hasil);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    
        
    private void ambilDataTabelBarang(){
        int index = tabelBarang.getSelectedRow();
        String nama = String.valueOf(tabelBarang.getValueAt(index, 0));
        String jenis = String.valueOf(tabelBarang.getValueAt(index, 1));
        String satuan = String.valueOf(tabelBarang.getValueAt(index, 2));
        String ukuran = String.valueOf(tabelBarang.getValueAt(index, 3));
        String stok = String.valueOf(tabelBarang.getValueAt(index, 4));
        String harga = String.valueOf(tabelBarang.getValueAt(index, 5));
        
        namaBarangPemasokBarang.setText(nama);
        JenisBarangPemasokBarang1.setText(jenis);
        hargaPersatuan.setText(harga);
        satuanPemasokBarangView.setText(satuan);
        ukuranPemasokBarangView.setText(ukuran);
        cPB.kontrolButton();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JenisBarangPemasokBarang1;
    private javax.swing.JTextArea alamatPerusahaanView;
    private javax.swing.JTextField hargaPersatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlahPemasokBarangVieww;
    private javax.swing.JTextField namaBarangPemasokBarang;
    private javax.swing.JTextField namaPerusahaanPemasokBarangView;
    private javax.swing.JTextField nomorIdentitasView;
    private javax.swing.JTextField satuanPemasokBarangView;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelPemasokBarang;
    private javax.swing.JButton tombolBatalView;
    private javax.swing.JButton tombolHapusView;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JTextField ukuranPemasokBarangView;
    // End of variables declaration//GEN-END:variables
}
