/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import controller.controllerBarang;
import dataBase.koneksiDatabase;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class viewBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewBarang
     */
    private controllerBarang cB;
    private DefaultTableModel model;
    public viewBarang() {
        initComponents();
        cB = new controllerBarang(this);
        model = new DefaultTableModel();
        tabelBarang.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Jenis");
        model.addColumn("Satuan");
        model.addColumn("Ukuran");
        model.addColumn("Stok");
        model.addColumn("harga");
        tampilDataBarang();
        cB.kontrolButton();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        idBarangView = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namaBarangView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenisBarangView = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ukuranBarangView = new javax.swing.JTextField();
        tombolBatalView = new javax.swing.JButton();
        tombolHapusView = new javax.swing.JButton();
        tombolUbahView = new javax.swing.JButton();
        tombolSimpanView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        SatuanBarangView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StokBarangView = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hargaBarangView = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modul Barang");

        jLabel6.setText("ID Barang");

        idBarangView.setEnabled(false);
        idBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBarangViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        namaBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangViewActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis");

        jenisBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangViewActionPerformed(evt);
            }
        });

        jLabel3.setText("Ukuran");

        ukuranBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukuranBarangViewActionPerformed(evt);
            }
        });

        tombolBatalView.setText("Batal");
        tombolBatalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalViewActionPerformed(evt);
            }
        });

        tombolHapusView.setText("Hapus");
        tombolHapusView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusViewActionPerformed(evt);
            }
        });

        tombolUbahView.setText("Ubah");
        tombolUbahView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahViewActionPerformed(evt);
            }
        });

        tombolSimpanView.setText("Simpan");
        tombolSimpanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanViewActionPerformed(evt);
            }
        });

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelBarang);

        jLabel7.setText("satuan");

        SatuanBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuanBarangViewActionPerformed(evt);
            }
        });

        jLabel5.setText("Stok");

        StokBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokBarangViewActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga");

        hargaBarangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBarangViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SatuanBarangView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ukuranBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StokBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hargaBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(25, 25, 25))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tombolBatalView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tombolHapusView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tombolUbahView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tombolSimpanView))
                        .addComponent(jenisBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namaBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SatuanBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukuranBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(StokBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(hargaBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(namaBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jenisBarangView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(265, 265, 265)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tombolSimpanView)
                                .addComponent(tombolUbahView)
                                .addComponent(tombolHapusView)
                                .addComponent(tombolBatalView))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SatuanBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuanBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SatuanBarangViewActionPerformed

    private void tombolSimpanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanViewActionPerformed
        // TODO add your handling code here:
        cB.simpan();
        tampilDataBarang();
    }//GEN-LAST:event_tombolSimpanViewActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        ambilDataTabel();
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void ukuranBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukuranBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukuranBarangViewActionPerformed

    private void tombolHapusViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusViewActionPerformed
        // TODO add your handling code here:
        cB.hapus();
        tampilDataBarang();
    }//GEN-LAST:event_tombolHapusViewActionPerformed

    private void tombolUbahViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahViewActionPerformed
        // TODO add your handling code here:
        cB.ubah();
        tampilDataBarang();
    }//GEN-LAST:event_tombolUbahViewActionPerformed

    private void namaBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangViewActionPerformed

    private void jenisBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisBarangViewActionPerformed

    private void idBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBarangViewActionPerformed

    private void tombolBatalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalViewActionPerformed
        // TODO add your handling code here:
        cB.kontrolButton();
        cB.bersihkan();
        tampilDataBarang();
    }//GEN-LAST:event_tombolBatalViewActionPerformed

    private void StokBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StokBarangViewActionPerformed

    private void hargaBarangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBarangViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBarangViewActionPerformed

    public JTextField getSatuanBarangView() {
        return SatuanBarangView;
    }

    public JTextField getStokBarangView() {
        return StokBarangView;
    }

    public JTextField getIdBarangView() {
        return idBarangView;
    }

    public JTextField getJenisBarangView() {
        return jenisBarangView;
    }

    public JTextField getNamaBarangView() {
        return namaBarangView;
    }

    public JTextField getUkuranBarangView() {
        return ukuranBarangView;
    }

    public JTextField getHargaBarangView() {
        return hargaBarangView;
    }
    

    
    
    
    public JButton getTombolBatalView() {
        return tombolBatalView;
    }

    public JButton getTombolHapusView() {
        return tombolHapusView;
    }

    public JButton getTombolSimpanView() {
        return tombolSimpanView;
    }

    public JButton getTombolUbahView() {
        return tombolUbahView;
    }
    
    private void tampilDataBarang(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = ("SELECT * FROM barang");
        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] hasil;
                hasil = new Object[7];
                hasil[0] = res.getString("idBarang");
                hasil[1] = res.getString("namaBarang");
                hasil[2] = res.getString("jenisBarang");
                hasil[3] = res.getString("satuan");
                hasil[4] = res.getString("ukuran");
                hasil[5] = res.getString("stok");
                hasil[6] = res.getString("harga");
                model.addRow(hasil);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    
        
    private void ambilDataTabel(){
        int index = tabelBarang.getSelectedRow();
        String id = String.valueOf(tabelBarang.getValueAt(index, 0));
        String nama = String.valueOf(tabelBarang.getValueAt(index, 1));
        String jenis = String.valueOf(tabelBarang.getValueAt(index, 2));
        String satuan = String.valueOf(tabelBarang.getValueAt(index, 3));
        String ukuran = String.valueOf(tabelBarang.getValueAt(index, 4));
        String stok = String.valueOf(tabelBarang.getValueAt(index, 5));
        String harga = String.valueOf(tabelBarang.getValueAt(index, 6));
        
        idBarangView.setText(id);
        namaBarangView.setText(nama);
        jenisBarangView.setText(jenis);
        SatuanBarangView.setText(satuan);
        ukuranBarangView.setText(ukuran);
        StokBarangView.setText(stok);
        hargaBarangView.setText(harga);
        cB.kontrolButtonDua();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SatuanBarangView;
    private javax.swing.JTextField StokBarangView;
    private javax.swing.JTextField hargaBarangView;
    private javax.swing.JTextField idBarangView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jenisBarangView;
    private javax.swing.JTextField namaBarangView;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton tombolBatalView;
    private javax.swing.JButton tombolHapusView;
    private javax.swing.JButton tombolSimpanView;
    private javax.swing.JButton tombolUbahView;
    private javax.swing.JTextField ukuranBarangView;
    // End of variables declaration//GEN-END:variables
}
